#!/bin/sh
set -e

# Program:
#       This program shows "this is a test from Zong-Sheng Liu" in your screen.
# History:
# 2023/09/16	Jason	First release

echo "this is a test from Zong-Sheng Liu" >&2
